{
 "title": "Rula Information",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Left RULA Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT CAST(jsonb_path_query(compound,'$.data') as REAL) AS \"Left RULA Score\",\na.ts FROM public.\"attributes\" AS a where a.id like '%rula_left';"
    }
   ]
  },
  {
   "title": "Right Side Of Body Information",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT CAST(jsonb_path_query(compound,'$.right_arm_up') as REAL) AS \"Right Arm Upper Angle\",\nCAST(jsonb_path_query(compound,'$.right_low_angle') as REAL) AS \"Right Arm Lower Angle\",\na.ts FROM public.\"attributes\" AS a where a.id like '%body_data';"
    }
   ]
  },
  {
   "title": "Right RULA Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT CAST(jsonb_path_query(compound,'$.data') as REAL) AS \"Right Rula Score\",\na.ts FROM public.\"attributes\" AS a where a.id like '%rula_right';"
    }
   ]
  },
  {
   "title": "Left Side Of Body Information",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT CAST(jsonb_path_query(compound,'$.left_arm_up') as REAL) AS \"Left Arm Upper Angle\",\nCAST(jsonb_path_query(compound,'$.left_low_angle') as REAL) AS \"Left Arm Lower Angle\",\na.ts FROM public.\"attributes\" AS a where a.id like '%body_data';"
    }
   ]
  },
  {
   "title": "Right Side Step Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT CAST(jsonb_path_query(compound,'$.right_shoulder') as REAL) AS \"Right Shoulder Raise\",\nCAST(jsonb_path_query(compound,'$.right_up_abduction') as REAL) AS \"Right Upper Arm Abduction\",\nCAST(jsonb_path_query(compound,'$.right_low_abduction') as REAL) AS \"Right Lower Arm Abduction\",\na.ts FROM public.\"attributes\" AS a where a.id like '%body_data';"
    }
   ]
  },
  {
   "title": "Body Step Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT CAST(jsonb_path_query(compound,'$.neck_twist') as REAL) AS \"Twisted Neck\",\nCAST(jsonb_path_query(compound,'$.neck_bending') as REAL) AS \"Bended Neck\",\nCAST(jsonb_path_query(compound,'$.side_bending') as REAL) AS \"Trunk Side Bended\",\na.ts FROM public.\"attributes\" AS a where a.id like '%body_data';"
    }
   ]
  },
  {
   "title": "Left Side Step Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT CAST(jsonb_path_query(compound,'$.left_shoulder') as REAL) AS \"Left Shoulder Raise\",\nCAST(jsonb_path_query(compound,'$.left_up_abduction') as REAL) AS \"Left Upper Arm Abduction\",\nCAST(jsonb_path_query(compound,'$.left_low_abduction') as REAL) AS \"Left Lower Arm Abduction\",\na.ts FROM public.\"attributes\" AS a where a.id like '%body_data';"
    }
   ]
  },
  {
   "title": "Body General Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT CAST(jsonb_path_query(compound,'$.neck_angle') as REAL) AS \"Neck Angle\",\nCAST(jsonb_path_query(compound,'$.trunk_angle') as REAL) AS \"Trunk Angle\",\na.ts FROM public.\"attributes\" AS a where a.id like '%body_data';"
    }
   ]
  }
 ]
}